### ISSUE TITLE
Can't import npm packages

### ISSUE THREAD

**Issue by vicaba** [GianlucaGuarini/es6-project-starter-kit#52]
Hi,

I have a problem when importing npm package libraries, given this code:

```
import * as Chart from 'chartjs/chart'  // or chartjs
import * as Moment from 'moment/src/moment' // or moemnt

window.initializer = {
  init: () => {
    console.log('hola')
    let moment = new Moment()
    let chart = new Chart({})
    let a = 3
  }
}
```

I get "Treating 'chartjs/chart' as external dependency" and the same for moment. I have already installed the using npm and they are in the node_modules directory, but I can't get them inside the generated bundle.

**Comment by GianlucaGuarini** [comment]
You will need to install the [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve) rollup plugin and configure your build.js script. This is not an issue so I am closing this

**Comment by skyserpent** [comment]
Can you show an example of using the rollup-plugin-node-resolve library? I only ask because I simply cannot get it to work with this project
