### ISSUE TITLE
Why use make?

### ISSUE THREAD

**Issue by tracker1** [GianlucaGuarini/es6-project-starter-kit#6]
I would suggest adding appropriate scripts to your package.json file, and from there, you can run your node scripts.  you can do combined tasks even.

for example:

```js
{
...
  "config": {
    "MOCHA_OPTS": "--recursive spec/",
    "ISPARTA_OPTS": "--report html",
    "COVERAGE_OPTS": "--statements 100 --functions 100 --branches 100 --lines 100"
  },
...
  "scripts": {
    "clean": "rimraf ./dist",
    "build": "babel ./src --experimental --source-maps-inline -d ./dist",
    "lint": "npm run lint-src && npm run lint-test",
    "lint-src": "eslint src",
    "lint-test": "eslint spec --global describe,it,beforeEach,afterEach --rule no-unused-expressions:false ",
    "unit": "babel-node -r node_modules/.bin/_mocha $npm_package_config_MOCHA_OPTS",
    "coverage": "babel-node -r node_modules/.bin/isparta cover $npm_package_config_ISPARTA_OPTS node_modules/.bin/_mocha -- $npm_package_config_MOCHA_OPTS",
    "coverage-check": "node node_modules/isparta/node_modules/istanbul/lib/cli check-coverage $npm_package_config_COVERAGE_OPTS",
    "show-report": "node scripts/open-coverage-report",
    "test": "npm run lint && npm run coverage && (npm run coverage-check || node scripts/open-coverage-report)",
    "publish-major": "npm run build && npm version major && npm publish && git push origin master && git push --tags",
    "publish-minor": "npm run build && npm version minor && npm publish && git push origin master && git push --tags",
    "publish-patch": "npm run build && npm version patch && npm publish && git push origin master && git push --tags"
  },
...
}

```

**Comment by GianlucaGuarini** [comment]
Hi thanks for your feedback. The decision to have my build steps in a separate file is based on several concepts:
  1. I don't like the idea to pollute my package.json with too many commands because in the end will be hard to mantain and unreadable (https://github.com/GianlucaGuarini/es6-project-starter-kit/blob/master/make looks a lot better) 
  2. Using raw terminal commands it's not crossplatform, have you tought about the windows users?
  3. You cannot use custom messages showing the progression of your tasks
  4. You can not really debug your code unless you run other .js files
  5. You can not use promises conctatenating your tasks

**Comment by tracker1** [comment]
Actually, you can just run against all the other tasks the same way you have the test script wired up... Except, you need to put node in front, as the shebang hinting doesn't work in windows command prompt or powershell.

```js
"scripts":{
  "build":"node ./make build",
  "test":"node ./make test",
  ...
},
```

1. It really wouldn't pollute it much as described above...  You can use your existing make js file

2. sure it is... as long as your commands aren't specifying extensions, and you use `&&` or `||` not single character versions...  I've been running with node on windows for several years (since I had to use cygwin to get it running, and even then).  The example I posted, while a bit convoluted does in fact run fine in windows.

3. you can have `console.log()` inside your scripts, and even run raw js scripts as you are now, or use a task runner as such.

4. exactly... that isn't prohibited wrt the scripts section of package.json running via `node run FOO`

5. see above.

**Comment by GianlucaGuarini** [comment]
Yeah probably I could think to alias the make command via npm but `npm run build` looks still harder than `./make build`. I will probably update the package.json in the next release thanks 4 the hint

**Comment by tracker1** [comment]
I didn't realize you were just using a local script with shebang when I asked... I'd assumed you were using cmake/gmake with a makefile...  and it is shorter, but that shortened syntax won't work in window's shell.  no worries, was a my bad when I looked further into it to create an example scripts section.
