### ISSUE TITLE
Error when performing npm install on Windows 7

### ISSUE THREAD

**Issue by hajekt2** [GianlucaGuarini/es6-project-starter-kit#8]
I am getting the below error when running npm install command on Windows 7. I do not know how to resolve the error. 

Console output:

    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
    
    > phantomjs@1.9.19 install D:\work\es6_cmd_skeleton\node_modules\phantomjs
    > node install.js  
    Done. Phantomjs binary available at D:\work\es6_cmd_skeleton\node_modules\phantomjs\lib\phantom\phantomjs.exe
    
    > sauce-connect-launcher@0.13.0 postinstall D:\work\es6_cmd_skeleton\node_modules\sauce-connect-launcher
    > node scripts/install.js
    
    
    > es6-project-starter-kit@5.0.0 prepublish D:\work\es6_cmd_skeleton
    > node make
    
     Executing: ./node_modules/.bin/eslint  tasks src test
    
    events.js:154
          throw er; // Unhandled 'error' event
          ^
    
    Error: spawn node_modules\.bin\eslint ENOENT
        at exports._errnoException (util.js:856:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at nextTickCallbackWith2Args (node.js:474:9)
        at process._tickCallback (node.js:388:17)
        at Function.Module.runMain (module.js:449:11)
        at startup (node.js:139:18)
        at node.js:999:3
    
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v5.5.0
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! es6-project-starter-kit@5.0.0 prepublish: `node make`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the es6-project-starter-kit@5.0.0 prepublish script 'node make'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the es6-project-starter-kit package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node make
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls es6-project-starter-kit
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\work\es6_cmd_skeleton\npm-debug.log

[npm-debug.log.txt](https://github.com/GianlucaGuarini/es6-project-starter-kit/files/120657/npm-debug.log.txt)

**Comment by GianlucaGuarini** [comment]
@hajekt2 thanks for your feedback. Can you try the latest version 5.0.2?

**Comment by hajekt2** [comment]
I just tested the latest version with the same result:
```
> es6-project-starter-kit@5.0.2 prepublish D:\work\es6_cmd_skeleton
> node make

 Executing: ./node_modules/.bin/eslint  tasks src test

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\.bin\eslint ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! es6-project-starter-kit@5.0.2 prepublish: `node make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6-project-starter-kit@5.0.2 prepublish script 'node make'.
```
[npm-debug.log.txt](https://github.com/GianlucaGuarini/es6-project-starter-kit/files/120895/npm-debug.log.txt)

I am very new to nodejs, to me it crash when running eslint.
When I run `node make` from the commandline it crash with the same error.
When I run `.\node_modules\.bin\eslint tasks src test` from the commandline, it gives no console output and ends with return code 0.

I appreciate you helping me with that.

**Comment by GianlucaGuarini** [comment]
Can you try only `./make` instead of `node make`? Have you at least node v4 installed?

**Comment by hajekt2** [comment]
Running Windows 7, node v5.5.0, npm  v3.3.12. Since i'm on Windows I cannot run just `./make`.

**Comment by GianlucaGuarini** [comment]
@hajekt2 thanks your feedback is precious.. I will try to run this project on a windows VM. It's a strange issue because all the cli paths ([this for example](https://github.com/GianlucaGuarini/es6-project-starter-kit/blob/master/tasks/eslint.js#L15)) are [normalized](https://github.com/GianlucaGuarini/es6-project-starter-kit/blob/master/tasks/_utils.js#L66) so they should work properly also on windows. It seems that your terminal could not find the right path to the npm cli tools in `node_modules/.bin`

**Comment by tracker1** [comment]
@hajekt2 The example you give could be the source of an error, in windows, the shebang marker at the top of the file isn't used, you have to specify node as the executable...

If this runs via `npm` then the `./node_modules/.bin` is added to the PATHs before execution of tasks, so you should either use `return utils.exec('eslint', options.folders)` or use `node ./node_modules/.bin/eslint`

On windows, there's the shebang tagged `eslint` as well as an `eslint.cmd` file generated... when you just use `eslint` in an npm task, for example the `./node_modules/.bin` directory is appended to the `%PATH%` and then the command is run, which in windows will be `eslint.cmd` not `eslint` :-)

The npm cli tools are fine, it's the execution of eslint that fails...  You could always chain npm scripts too...

```
=== package.json ===
...
  "scripts": {
    "test_lint": "eslint ...",
    "test_unit": "...",
    "test": "npm run test_lint && npm run test_unit",
    ...
  }
...
```

Don't use the single `&`, it doesn't work in windows, also if you want to set environment varibles use [cross-env](https://www.npmjs.com/packages/cross-env)

**Comment by GianlucaGuarini** [comment]
@hajekt2 can you confirm that the issue was solved in the latest release please?

**Comment by hajekt2** [comment]
@GianlucaGuarini everything working for me just great!
